### ISSUE TITLE
Open app collab

### ISSUE THREAD

**Issue by erlend-sh** [arthur-ver/deno-fresh-mongo#1]
Hey! 👋 

We’re building something similar here:
https://github.com/commune-org/linksapp

The plan however is to make a meta-linksapp by providing a wide assortment of link page generators to choose between, through one unified service.

If you’re interested in collaborating with us (optionally as some paid gig-work) my contact info is in my profile 😊

**Comment by arthur-ver** [comment]
Hi Erlend!

Sounds interesting! What’s your email? I couldn’t find it in your profile :)

Best regards,
Arthur

**Comment by arthur-ver** [comment]
Hi @erlend-sh!

I‘ve just sent you an email ✌️
